CREATE TABLE public.trader (
	id int8 GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp(6) NULL,
	email varchar(255) NULL,
	"name" varchar(255) NULL,
	pan_number varchar(255) NULL,
	trader_status int2 NULL,
	updated_at timestamp(6) NULL,

	CONSTRAINT pk_trader PRIMARY KEY (id),

	CONSTRAINT chk_trader_status
		CHECK (((trader_status >= 0) AND (trader_status <= 1))),

	CONSTRAINT uk_trader_pan_number UNIQUE (pan_number),

	CONSTRAINT uk_trader_email UNIQUE (email)
);

CREATE TABLE public.sector (
	id int8 GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp(6) NULL,
	"name" varchar(255) NULL,
	updated_at timestamp(6) NULL,

	CONSTRAINT pk_sector PRIMARY KEY (id),

	CONSTRAINT uk_sector_name UNIQUE (name)
);

CREATE TABLE public.stock (
	id int8 GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp(6) NULL,
	"name" varchar(255) NULL,
	price float4 NULL,
	updated_at timestamp(6) NULL,
	sector_id int8 NOT NULL,

	CONSTRAINT pk_stock PRIMARY KEY (id),

	CONSTRAINT uk_stock_name UNIQUE (name),

	CONSTRAINT fk_stock_sector
		FOREIGN KEY (sector_id)
		REFERENCES public.sector(id)
);

CREATE TABLE public.basket (
	id int8 GENERATED BY DEFAULT AS IDENTITY,
	basket_status int2 NULL,
	created_at timestamp(6) NULL,
	"name" varchar(255) NULL,
	updated_at timestamp(6) NULL,

	CONSTRAINT pk_basket PRIMARY KEY (id),

	CONSTRAINT chk_basket_status
		CHECK (((basket_status >= 0) AND (basket_status <= 1))),

	CONSTRAINT uk_basket_name UNIQUE (name)
);

CREATE TABLE public.stock_basket_map (
	id int8 GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	basket_id int8 NOT NULL,
	stock_id int8 NOT NULL,

	CONSTRAINT pk_stock_basket_map PRIMARY KEY (id),

	CONSTRAINT fk_stock_basket_map_basket
		FOREIGN KEY (basket_id)
		REFERENCES public.basket(id),

	CONSTRAINT fk_stock_basket_map_stock
		FOREIGN KEY (stock_id)
		REFERENCES public.stock(id)
);

CREATE INDEX idx_stockbasketmap_basket_id
	ON public.stock_basket_map USING btree (basket_id);

CREATE INDEX idx_stockbasketmap_basket_stock
	ON public.stock_basket_map USING btree (basket_id, stock_id);

CREATE INDEX idx_stockbasketmap_stock_id
	ON public.stock_basket_map USING btree (stock_id);

CREATE TABLE public.holding (
	id int8 GENERATED BY DEFAULT AS IDENTITY,
	quantity int4 NULL,
	updated_at timestamp(6) NULL,
	basket_id int8 NULL,
	sector_id int8 NOT NULL,
	stock_id int8 NOT NULL,
	trader_id int8 NOT NULL,

	CONSTRAINT pk_holding PRIMARY KEY (id),

	CONSTRAINT uk_holding_trader_stock
		UNIQUE (trader_id, stock_id),

	CONSTRAINT fk_holding_basket
		FOREIGN KEY (basket_id)
		REFERENCES public.basket(id),

	CONSTRAINT fk_holding_trader
		FOREIGN KEY (trader_id)
		REFERENCES public.trader(id),

	CONSTRAINT fk_holding_sector
		FOREIGN KEY (sector_id)
		REFERENCES public.sector(id),

	CONSTRAINT fk_holding_stock
		FOREIGN KEY (stock_id)
		REFERENCES public.stock(id)
);

CREATE INDEX idx_holding_trader_id
	ON public.holding USING btree (trader_id);

CREATE INDEX idx_holding_trader_stock
	ON public.holding USING btree (trader_id, stock_id);

CREATE TABLE public.orders (
	id int8 GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp(6) NULL,
	quantity int4 NULL,
	rate float4 NULL,
	side int2 NULL,
	status int2 NULL,
	total float4 NULL,
	updated_at timestamp(6) NULL,
	sector_id int8 NOT NULL,
	stock_id int8 NOT NULL,
	trader_id int8 NOT NULL,

	CONSTRAINT pk_orders PRIMARY KEY (id),

	CONSTRAINT chk_orders_side
		CHECK (((side >= 0) AND (side <= 1))),

	CONSTRAINT chk_orders_status
		CHECK (((status >= 0) AND (status <= 2))),

	CONSTRAINT fk_orders_stock
		FOREIGN KEY (stock_id)
		REFERENCES public.stock(id),

	CONSTRAINT fk_orders_sector
		FOREIGN KEY (sector_id)
		REFERENCES public.sector(id),

	CONSTRAINT fk_orders_trader
		FOREIGN KEY (trader_id)
		REFERENCES public.trader(id)
);

CREATE INDEX idx_orders_trader_id
	ON public.orders USING btree (trader_id);

CREATE INDEX idx_orders_trader_orderstatus
	ON public.orders USING btree (trader_id, status);

CREATE INDEX idx_orders_trader_stock
	ON public.orders USING btree (trader_id, stock_id);
