--version used 15.3

CREATE TABLE public.trader (
                               id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                               created_at timestamp(6) NULL,
                               email varchar(255) NULL,
                               name varchar(255) NULL,
                               pan_number varchar(255) NULL,
                               trader_status int2 NULL,
                               updated_at timestamp(6) NULL,
                               CONSTRAINT trader_pkey PRIMARY KEY (id),
                               CONSTRAINT trader_trader_status_check CHECK (((trader_status >= 0) AND (trader_status <= 1))),
                               CONSTRAINT uk1m0rp5ksbbsypc2jga66m18ca UNIQUE (pan_number),
                               CONSTRAINT ukcmiqwl1oruvoa59f3klu7i3kc UNIQUE (email)
);

CREATE TABLE public.sector (
                               id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                               created_at timestamp(6) NULL,
                               "name" varchar(255) NULL,
                               updated_at timestamp(6) NULL,
                               CONSTRAINT sector_pkey PRIMARY KEY (id),
                               CONSTRAINT ukgt10yoxplooy0sueukkysbjrr UNIQUE (name)
);

CREATE TABLE public.stock (
                              id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                              created_at timestamp(6) NULL,
                              "name" varchar(255) NULL,
                              price float4 NULL,
                              sector_id int8 NOT NULL,
                              updated_at timestamp(6) NULL,
                              CONSTRAINT stock_pkey PRIMARY KEY (id),
                              CONSTRAINT uk9fjf4aj1d5f2m6wi2uqmdan0a UNIQUE (name),
                              CONSTRAINT fk_stock_sector FOREIGN KEY (sector_id) REFERENCES public.sector(id)
);

CREATE TABLE public.basket (
                               id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                               basket_status int2 NULL,
                               created_at timestamp(6) NULL,
                               "name" varchar(255) NULL,
                               updated_at timestamp(6) NULL,
                               CONSTRAINT basket_basket_status_check CHECK (((basket_status >= 0) AND (basket_status <= 1))),
                               CONSTRAINT basket_pkey PRIMARY KEY (id),
                               CONSTRAINT ukk1a2ugsadeq00mxrepiwkb58l UNIQUE (name)
);

CREATE TABLE public.stock_basket_map (
                                         id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                         basket_id int8 NULL,
                                         created_at timestamp(6) NULL,
                                         stock_id int8 NULL,
                                         updated_at timestamp(6) NULL,
                                         CONSTRAINT stock_basket_map_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_stockbasketmap_basket_stock ON public.stock_basket_map USING btree (basket_id, stock_id);
CREATE INDEX idx_stockbasketmap_basketid ON public.stock_basket_map USING btree (basket_id);
CREATE INDEX idx_stockbasketmap_stockid ON public.stock_basket_map USING btree (stock_id);





CREATE TABLE public.orders (
                               id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                               created_at timestamp(6) NULL,
                               quantity int4 NULL,
                               rate float4 NULL,
                               sector_id int8 NOT NULL,
                               side int2 NULL,
                               status int2 NULL,
                               stock_id int8 NULL,
                               total float4 NULL,
                               trader_id int8 NULL,
                               updated_at timestamp(6) NULL,
                               CONSTRAINT orders_pkey PRIMARY KEY (id),
                               CONSTRAINT orders_side_check CHECK (((side >= 0) AND (side <= 1))),
                               CONSTRAINT orders_status_check CHECK (((status >= 0) AND (status <= 2))),
                               CONSTRAINT fk_orders_sector FOREIGN KEY (sector_id) REFERENCES public.sector(id)
);
CREATE INDEX idx_orders_traderid ON public.orders USING btree (trader_id);
CREATE INDEX idx_orders_traderid_stockid ON public.orders USING btree (trader_id, stock_id);

CREATE TABLE public.holding (
                                id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                quantity int4 NULL,
                                sector_id int8 NOT NULL,
                                stock_id int8 NULL,
                                trader_id int8 NULL,
                                updated_at timestamp(6) NULL,
                                CONSTRAINT holding_pkey PRIMARY KEY (id),
                                CONSTRAINT uk6m8tvyum2am8vm0s4tj7dcg5j UNIQUE (trader_id, stock_id),
                                CONSTRAINT fk_holding_sector FOREIGN KEY (sector_id) REFERENCES public.sector(id)
);
CREATE INDEX idx_holding_trader_id ON public.holding USING btree (trader_id);
CREATE INDEX idx_holding_trader_stock ON public.holding USING btree (trader_id, stock_id);